# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faab21cf9b8fdaa8b2cd9cb7276618faf01e3dbeebc6985d1781130af9c76424754b46f6fd681566fa664a087575c3a9e3724c098075fe600ac6cc7fdacefeb2

test:
  secret_key_base: b66e780cccc1a15b8e09b07357732d199af439e3dd226f0c657c7195dca5e54a7df4de26306d14b1eb9c2d0113eb0353ba7b737e0a5ba37a9498741fb37abe2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
